var app = angular.module("myApp",[]);

app.controller("myCtrl", function($scope) {
	$scope.friends = [
		{nickName:'krysia', firstName:'Krystyna', lastName:'Brudnicki'},
		{nickName:'andy', firstName:'Andy', lastName:'Park'},
		{nickName:'shan', firstName:'Shan', lastName:'Pruthi'},
		{nickName:'earvin', firstName:'Earvin', lastName:'Tio'},
		{nickName:'shreya', firstName:'Shreya', lastName:'Sathyanarayan'},
		{nickName:'sam', firstName:'Sam', lastName:'Yuyitung'},
		{nickName:'seb', firstName:'Sebastian', lastName:'Kolosa'},
		{nickName:'bill', firstName:'Bill', lastName:'Chen'},
		{nickName:'hanna', firstName:'Hanna', lastName:'Kyowski'},
		{nickName:'alex', firstName:'Alexander', lastName:'Glover'},
		{nickName:'steph', firstName:'Stephanie', lastName:'Carras'},
		{nickName:'dom', firstName:'Dominic', lastName:'Dotzert'},
		{nickName:'keith', firstName:'Keith', lastName:'Daigle'},
		{nickName:'jenny', firstName:'Jenny', lastName:'Jin'},
		{nickName:'umesh', firstName:'Umesh', lastName:'Khanna'},
		{nickName:'samantha', firstName:'Samantha', lastName:'Mar'},
		{nickName:'hayes', firstName:'Hayes', lastName:'Lee'},
		{nickName:'mudmie', firstName:'Mudmie', lastName:'Chuthamsatid'},
		{nickName:'ethan', firstName:'Ethan', lastName:'Liang'},
		{nickName:'jessie', firstName:'Jessie', lastName:'Won'},
		{nickName:'ashley', firstName:'Ashley', lastName:'Hu'},
		{nickName:'shio', firstName:'Michael', lastName:'Shiozaki'},
		{nickName:'andrea', firstName:'Andrea', lastName:'Edwards'},
		{nickName:'kevin', firstName:'Kevin', lastName:'Luong'},
		{nickName:'cindy', firstName:'Cindy', lastName:'Liu'},
		{nickName:'justin', firstName:'Justin', lastName:'Schaper'},
		{nickName:'jeff', firstName:'Jeffrey', lastName:'Wang'},
		{nickName:'andrew', firstName:'Andrew', lastName:'Clarry'},
		{nickName:'zak', firstName:'Zachary', lastName:'Keller'},
		{nickName:'hunter', firstName:'Hunter', lastName:'McHugh'},
		{nickName:'rohan', firstName:'Rohan', lastName:'Saigaonkar'},
		{nickName:'tamilla', firstName:'Tamilla', lastName:'Bunyadova'},
		{nickName:'dylan', firstName:'Dylan', lastName:'Conway'},
		{nickName:'jon', firstName:'Jonathan', lastName:'Loos'},
		{nickName:'ron', firstName:'Ronald', lastName:'Kielstra'},
		{nickName:'amelia', firstName:'Amelia', lastName:'King'},
		{nickName:'jasdip', firstName:'Jasdip', lastName:'Chauhan'},
		{nickName:'pavi', firstName:'Pavneet', lastName:'Singh'},
		{nickName:'ken', firstName:'Ken', lastName:'Ives'},
		{nickName:'robi', firstName:'Roberto', lastName:'Sanchez'},
		{nickName:'heather', firstName:'Heather', lastName:'Chan'}
	];
});